### ISSUE TITLE
Incompatibility issues with ShowmeYourSkin

### ISSUE THREAD

**Issue by URSFR** [CmdrJane/time-and-wind#17]
Incompatibility issue with ShowMeYourSkin when "syncWithSystemTime" is enabled in config.

Mod: https://modrinth.com/mod/show-me-your-skin

java.lang.NullPointerException: Cannot invoke "ru.aiefu.timeandwindct.config.SystemTimeConfig.getSunriseMs()" because "config" is null
	at ru.aiefu.timeandwindct.tickers.SystemTimeTicker.<init>(SystemTimeTicker.java:27) ~[time-and-wind-ct-1.4.3+1.19.2.jar:?]
	at net.minecraft.class_638.handler$lio000$attachTimeDataTAW(class_638.java:10148) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.<init>(class_638.java:179) ~[client-intermediary.jar:?]
	at nl.enjarai.showmeyourskin.client.DummyClientWorld.<init>(DummyClientWorld.java:23) ~[show-me-your-skin-1.3.4+1.19.jar:?]
	at nl.enjarai.showmeyourskin.client.DummyClientWorld.getInstance(DummyClientWorld.java:18) ~[show-me-your-skin-1.3.4+1.19.jar:?]
	at nl.enjarai.showmeyourskin.client.DummyClientPlayerEntity.<init>(DummyClientPlayerEntity.java:43) ~[show-me-your-skin-1.3.4+1.19.jar:?]
	at nl.enjarai.showmeyourskin.client.DummyClientPlayerEntity$1.<init>(DummyClientPlayerEntity.java:33) ~[show-me-your-skin-1.3.4+1.19.jar:?]
	at nl.enjarai.showmeyourskin.client.DummyClientPlayerEntity.getInstance(DummyClientPlayerEntity.java:33) ~[show-me-your-skin-1.3.4+1.19.jar:?]
	at nl.enjarai.showmeyourskin.ShowMeYourSkin.lambda$onInitialize$0(ShowMeYourSkin.java:26) ~[show-me-your-skin-1.3.4+1.19.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:38) ~[fabric-lifecycle-events-v1-2.1.2+aeb40ebe90-b3cfce975acd51a1.jar:?]
	at net.minecraft.class_310.handler$ejj000$onStart(class_310.java:17984) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:747) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]

**Comment by CmdrJane** [comment]
should be fixed
