### ISSUE TITLE
Crashing on Launch

### ISSUE THREAD

**Issue by pokegirl420** [CmdrJane/time-and-wind#5]
---- Minecraft Crash Report ----
// There are four lights!

Time: 5/7/21 12:40 PM
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_329.<init>(class_329.java:156)
	at net.minecraft.class_310.<init>(class_310.java:559)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method patchDayCounterTAW(J)J in taw.mixins.json:DebugHudMixins failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap time-and-wind-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_329.<init>(class_329.java:156)
	at net.minecraft.class_310.<init>(class_310.java:559)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1371826992 bytes (1308 MB) / 2147483648 bytes (2048 MB) up to 17179869184 bytes (16384 MB)
	CPUs: 32
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancedcompass: Advanced Compass 1.0.1
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		antiqueatlas: Antique Atlas 5.4.4-fabric
		anvil_fix: AnvilFix 1.2.0-1.16
		appleskin: AppleSkin 1.0.11
		appletreesrev: Apple Trees Revived 1.2
		autoconfig1u: Auto Config v1 Updated 3.3.1
		battletowers: Battle Towers 3.3.4-1.16.4
		betterbeds: Better Beds 1.1.0
		bettereating: Better Eating 0.3.0
		betterend: Better End 0.9.6-pre
		bettermounthud: Better Mount HUD 1.0.1
		betternether: Better Nether 5.0.7
		biomemakeover: Biome Makeover 1.16.5-1.3.8
		blockshifter: Blockshifter 1.3.2+fabric-1.16.4
		cameraoverhaul: Camera Overhaul 1.2.2-fabric-universal
		candlebackport: Candle Backport 1.0
		cleancut: CleanCut mc1.16-2.1-fabric
		clickthrough: ClickThrough 1.16.5-fabric0.30.0-0.4
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.11.19
		colored-tooltips: Colored Tooltips 1.1.1
		com_google_code_gson_gson: gson 2.8.6
		companion_bats: Companion Bats 1.13.2
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		crowdin-translate: CrowdinTranslate 1.2
		cullleaves: Cull Leaves 2.1.0
		dataloader: Data Loader 2.1.0+mc1.16.1
		daylight_mobs_reborn: Daylight Mobs Reborn 1.2.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		dynmus: Dynamic Music 1.1.0
		entityculling: EntityCulling-Fabric 1.2.2
		extrasounds: Extra Sounds 1.0.0
		fabric: Fabric API 0.34.1+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-language-scala: Fabric Language Scala 1.0.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.2+d6244c6d7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		fallingleaves: Falling Leaves 1.6.0+1.16.5
		fallingtree: FallingTree 2.11.0
		fastchest: FastChest 1.2+1.16
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.0.1
		firstperson: FirstpersonModel 2.0.1
		flesh2leather: Flesh2Leather 1.0.2
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		gg_enchantments: Good Game Enchantments 1.1.1
		harvest: Harvest 1.2.12
		healthcare: Health Care 1.0.3
		held-item-info: Held Item Info 1.1.3
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		illuminations: Illuminations 1.5
		inmis: Inmis 2.2.1-1.16.5
		inventoryprofiles: Inventory Profiles 0.4.2
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kirin: Kirin UI 1.7-1.16.2
		lapisreserve: Lapis Reserve 1.0.6
		lazydfu: LazyDFU 0.1.2
		leadvillagers: Lead Villagers 2.1.0+mc1.16.1
		libstructure: LibStructure 1.5
		loading-timer: Loading Timer 1.4.1
		loud_leads: Loud Leads 1.0.1+mc1.16.4
		mambience: MAmbience 3.1.1+1.16.5
		mesh: Mesh 0.6.0-alpha.20+1.16.4
		mesh_api: Mesh API 0.6.0-alpha.20+1.16.4
		midnight-hats: Midnight Hats 2.0.1
		minecraft: Minecraft 1.16.5
		minemenufabric: MineMenuFabric 2.2
		mm: Manningham Mills 2.2
		modid: 1.17 Raw Ores for 1.16 1.0.0
		modmenu: Mod Menu 1.16.9
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		musicdr: Music Duration Reducer 1.2.0
		musketmod: Musket Mod 1.2.1
		new_buckets: New Buckets 1.0.0
		niapi: NativeImage API 1.16.5-1.0.0
		nofade: No Fade 1.16.5-1.0.1
		notenoughanimations: NotEnoughAnimations 1.2.4
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		omega-config: OmegaConfig 1.0.2
		optifabric: OptiFabric 1.9.6
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		overworld_two: Overworld 2 1.0.4
		playtime_count: Playtime Counter (Fabric) 1.0.0
		pling: Pling 1.2.0
		presencefootsteps: Presence Footsteps r29+1.16.4
		puddles: Puddles 1.0.0
		repurposed_structures: Repurposed Structures 1.16.5-1.10.5-fabric
		reroll: Reroll 1.2.1-1.16.5
		rocks: This Rocks! 1.3.1
		sakurarosea: Sakura Rosea 1.5.6-MC1.16.3-fabric
		seasons: Fabric Seasons 1.1.1-BETA
		silky_spawners: Silky Spawners 2.1.0+build.2-1.16
		simple_utilities: Simple Utilities 2.1.1
		smoothboot: Smooth Boot 1.16.5-1.6.0
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		stepup: StepUp 1.16.5-fabric0.30.0-1.1
		stitchedsnow: Stiched Snow 1.0.1
		structure-helpers: Structure Helpers 3.0.0
		terrarianslimes: Terrarian Slimes 1.0.3-BETA
		textweaks: TexTweaks 1.16.5-1.5.0
		timeandwind: Time & Wind 1.3.1
		transliterationlib: TRansliterationLib 1.0.4
		tweed: Tweed API 3.0.0-beta.22
		umollu_ash: ASH - Another Simple HUD 1.1.11
		visualoverhaul: VisualOverhaul 3.2.0
		voyager: Voyager 1.0.0
		wandering_collector: Wandering Collector 1.0.1+mc1.16.5
		waterdripsound: Drip Sounds 0.2.1-1.16
		wildfire_gender: Wildfire's Gender Mod 2.4.1
		wildworld: Wild World 2.0.0+1.16.5
		windchimes: Windchimes 1.1.1
		woodcutter: Woodcutter 1.2-1.16.1
	Launched Version: fabric-loader-0.11.3-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.27, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 32x AMD Ryzen 9 3950X 16-Core Processor 
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210305-003221
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: §r§lAstra§4§lLex§r§l_(§4§lBSL§r§l_Edit)_By_LexBoosT_§4§lV20.0§r§l.zip
	OpenGlVersion: 4.6.0 NVIDIA 466.27
	OpenGlRenderer: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 32

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.5
	OptiFine jar version: OptiFine_1.16.5_HD_U_G7
	OptiFine jar status: Valid OptiFine mod
	OptiFine remapped jar: C:\Users\Alex\AppData\Roaming\.minecraft\.optifine\OptiFine_1.16.5_HD_U_G7\Optifine-mapped.jar
	OptiFabric error: <None>

Yeah, I know there's a lot of mods being loaded, so it's probably some sort of conflict but I can't for the life of me figure out which one it is. Thanks in advance!

**Comment by CmdrJane** [comment]
Optifabric is NOT supported

**Comment by CmdrJane** [comment]
Anyway will be fixed in next release

**Comment by pokegirl420** [comment]
> 
> 
> Optifabric is NOT supported

that's kinda what I figured since i've seen shaderpacks edit the skyangle method, but didnt consider that that was the culprit! Thank you for letting me know!!! greatly appreciated!
